### ISSUE TITLE
句号的问题

### ISSUE THREAD

**Issue by llllllim** [sikouhjw/JXUSTmodeling#2]
请问一下，模板中文的句号是一个点，如何改为句号？

**Comment by sikouhjw** [comment]
首先，科技排版中尽量使用全角句点，参考
- 《[科技论文中使用句点代替句号的优势在哪里？](https://www.zhihu.com/question/22637562)》
- 《[xeCJK 宏包的隐藏技能：字符映射](https://liam.page/2016/05/12/the-hidden-skill-of-the-xeCJK-package-Mapping/)》

解决方案：在导言区加上 `\setCJKmainfont[AutoFakeBold=true]{SimSun}`，问题解决

**Comment by llllllim** [comment]
谢谢！您的回答对我帮助很大！
